#pragma once

#include <rfl.hpp>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace commrat {

/// Command types associated with one output port (populated by --commrat-inspect).
struct CmdMessagesForOutput {
    size_t output_index;
    std::vector<std::string> types;
};

/// Per-binary descriptor generated by commrat_module() and enriched by --commrat-inspect POST_BUILD.
/// Optional fields are absent in cmake-generate-time placeholders; present after a successful build.
struct ModuleDescriptor {
    std::string module_class;
    std::string binary;
    std::optional<std::vector<std::string>> outputs;
    std::optional<std::vector<std::string>> inputs;
    std::optional<std::vector<std::string>> synced_inputs;
    std::optional<std::string> execution_mode;                       // "timer" | "input" | "loop"
    std::optional<int64_t> default_period_ms;                        // only present when execution_mode == "timer"
    std::optional<std::vector<CmdMessagesForOutput>> cmd_messages;   // per-output command type names
    std::optional<rfl::Generic> params_defaults;                      // nested JSON object of default param values
};

} // namespace commrat
