#pragma once

#include <rfl.hpp>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace commrat {

/// Command types associated with one output port (populated by --commrat-inspect).
struct CmdMessagesForOutput {
    size_t output_index;
    std::vector<std::string> types;
};

struct CommandMessageDescriptor {
    std::string request_type;
    uint32_t request_id;
    std::string reply_type;
    uint32_t reply_id;
};

struct CommandEndpointDescriptor {
    size_t output_index;
    std::string output_type;
    uint32_t output_message_id;
    uint8_t address_type_id;
    uint8_t mailbox_index;
    std::vector<CommandMessageDescriptor> commands;
};

struct LifecycleEndpointDescriptor {
    std::optional<size_t> anchor_output_index;
    uint32_t anchor_message_id;
    uint8_t address_type_id;
    uint8_t mailbox_index;
};

/// Per-binary descriptor generated by commrat_module() through --commrat-inspect.
/// Native builds publish a complete descriptor atomically or fail the module build.
/// EVL cross-build placeholders omit optional fields until inspection runs in QEMU.
struct ModuleDescriptor {
    std::string module_class;
    std::string binary;
    std::optional<std::vector<std::string>> outputs;
    std::optional<std::vector<std::string>> inputs;
    std::optional<std::vector<std::string>> synced_inputs;
    std::optional<std::vector<std::string>> remotes;
    std::optional<std::string> execution_mode;                       // "timer" | "input" | "loop"
    std::optional<int64_t> default_period_ms;                        // only present when execution_mode == "timer"
    std::optional<std::vector<CmdMessagesForOutput>> cmd_messages;   // per-output command type names
    std::optional<std::vector<CommandEndpointDescriptor>> command_endpoints;
    std::optional<LifecycleEndpointDescriptor> lifecycle_endpoint;
    std::optional<rfl::Generic> params_defaults;                      // nested JSON object of default param values
};

} // namespace commrat
