#pragma once
/**
 * @file process_launcher.hpp
 * @brief Process-based CommRaT application launcher.
 *
 * Reads an AppDescription JSON, discovers module binaries from cmake-generated
 * *.module.json descriptor files, and spawns each module as a separate child
 * process with a generated ModuleConfig JSON.
 *
 * Descriptor files are auto-discovered from the same directory as the launcher
 * binary (dirname(argv[0])). cmake's commrat_module() generates them at build
 * time alongside each module binary.
 *
 * Usage:
 * @code
 * #include <commrat/launcher/process_launcher.hpp>
 *
 * int main(int argc, char** argv) {
 *     return commrat::ProcessLauncher::main(argc, argv);
 * }
 * @endcode
 *
 * CLI:
 *   ./my_launcher  app.json
 *   ./my_launcher  app.json  --duration-ms 5000   (exit after 5s, for CTest)
 */

#include <commrat/launcher/module_description.hpp>
#include <commrat/module/module_config.hpp>
#include <rfl/json.hpp>

#include <atomic>
#include <chrono>
#include <csignal>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

// POSIX process management
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

namespace commrat {

namespace detail {
    inline std::atomic<bool> g_process_launcher_shutdown{false};
    inline void process_launcher_signal_handler(int) {
        g_process_launcher_shutdown.store(true);
    }
}

// ---------------------------------------------------------------------------
// ModuleDescriptor — loaded from cmake-generated *.module.json
// ---------------------------------------------------------------------------

/**
 * Per-binary descriptor generated by commrat_module() in CMakeLists.txt.
 * Maps a module class name to the absolute path of its binary.
 */
struct ModuleDescriptor {
    std::string module_class;
    std::string binary;  ///< Absolute path to the binary
};

// ---------------------------------------------------------------------------
// ProcessLauncher
// ---------------------------------------------------------------------------

class ProcessLauncher {
public:
    // ------------------------------------------------------------------
    // Load
    // ------------------------------------------------------------------

    /**
     * Load AppDescription and discover module descriptors.
     *
     * @param app_desc_path   Path to the AppDescription JSON file.
     * @param descriptor_dirs Directories to scan for *.module.json files.
     *                        Defaults to dirname(argv[0]) when using main().
     */
    void load(const std::string& app_desc_path,
              const std::vector<std::string>& descriptor_dirs) {
        description_ = load_app_description(app_desc_path);
        for (const auto& dir : descriptor_dirs)
            scan_directory_for_descriptors(dir);
    }

    // ------------------------------------------------------------------
    // Start / stop
    // ------------------------------------------------------------------

    /**
     * Spawn all module processes.
     *
     * Modules with no inputs are started first (producers), followed by
     * modules with inputs (consumers). A 200 ms stagger is inserted between
     * each spawn so that TiMS mailboxes are registered before consumers
     * attempt to subscribe.
     */
    void start() {
        launcher_pid_ = ::getpid();

        // Producers first, consumers second
        std::vector<const ModuleDescription*> ordered;
        for (const auto& m : description_.modules) {
            if (m.inputs.empty()) ordered.insert(ordered.begin(), &m);
            else ordered.push_back(&m);
        }

        for (const auto* mod : ordered) {
            spawn_module(*mod);
            ::usleep(200'000);  // 200 ms stagger
        }
    }

    /**
     * Send SIGTERM to all child processes and wait for them to exit.
     * Falls back to SIGKILL after 3 seconds. Cleans up temp config files.
     */
    void stop() {
        for (auto& child : children_) {
            if (child.pid > 0) ::kill(child.pid, SIGTERM);
        }

        // Wait up to 3 s
        for (int poll = 0; poll < 30; ++poll) {
            ::usleep(100'000);
            bool all_done = true;
            for (auto& child : children_) {
                if (child.pid <= 0) continue;
                int status{};
                if (::waitpid(child.pid, &status, WNOHANG) == child.pid)
                    child.pid = -1;
                else
                    all_done = false;
            }
            if (all_done) break;
        }

        // SIGKILL stragglers
        for (auto& child : children_) {
            if (child.pid > 0) {
                ::kill(child.pid, SIGKILL);
                ::waitpid(child.pid, nullptr, 0);
            }
        }

        cleanup_temp_files();
        children_.clear();
    }

    // ------------------------------------------------------------------
    // Convenience main()
    // ------------------------------------------------------------------

    /**
     * Drop-in main() for a process launcher binary.
     *
     * Descriptor files are auto-discovered from dirname(argv[0]).
     *
     * @param argc  Argument count.
     * @param argv  argv[1] = AppDescription JSON path.
     *              Optional: --duration-ms N  (exit after N ms, for CTest)
     */
    static int main(int argc, char** argv) {
        if (argc < 2) {
            std::cerr << "Usage: " << argv[0]
                      << " <app.json> [--duration-ms N]\n";
            return 1;
        }

        uint32_t duration_ms = 0;
        for (int i = 2; i < argc - 1; ++i) {
            if (std::string_view(argv[i]) == "--duration-ms")
                duration_ms = static_cast<uint32_t>(std::stoul(argv[i + 1]));
        }

        // Auto-discover descriptors from the directory containing this binary
        std::filesystem::path exe = std::filesystem::canonical(argv[0]);
        std::vector<std::string> descriptor_dirs{exe.parent_path().string()};

        detail::g_process_launcher_shutdown.store(false);
        std::signal(SIGINT,  detail::process_launcher_signal_handler);
        std::signal(SIGTERM, detail::process_launcher_signal_handler);

        try {
            ProcessLauncher launcher;
            launcher.load(argv[1], descriptor_dirs);
            launcher.start();

            std::cout << "[Launcher] " << launcher.description_.app_name
                      << " running";
            if (duration_ms > 0)
                std::cout << " for " << duration_ms << " ms";
            std::cout << " (Ctrl+C to stop)\n";

            uint32_t elapsed_ms = 0;
            while (!detail::g_process_launcher_shutdown.load()) {
                ::usleep(100'000);
                elapsed_ms += 100;

                // Detect unexpected child exits
                for (auto& child : launcher.children_) {
                    if (child.pid <= 0) continue;
                    int status{};
                    if (::waitpid(child.pid, &status, WNOHANG) == child.pid) {
                        std::cerr << "[Launcher] Module '" << child.name
                                  << "' (pid " << child.pid
                                  << ") exited with status "
                                  << WEXITSTATUS(status) << "\n";
                        child.pid = -1;
                    }
                }

                if (duration_ms > 0 && elapsed_ms >= duration_ms) break;
            }

            std::cout << "[Launcher] Stopping...\n";
            launcher.stop();
            std::cout << "[Launcher] Done.\n";
            return 0;

        } catch (const std::exception& e) {
            std::cerr << "[Launcher] Error: " << e.what() << "\n";
            return 1;
        }
    }

private:
    struct ChildInfo { pid_t pid; std::string name; };

    AppDescription                              description_;
    std::unordered_map<std::string,
                       ModuleDescriptor>        descriptors_;   // module_class → descriptor
    std::vector<ChildInfo>                      children_;
    std::vector<std::string>                    temp_files_;
    pid_t                                       launcher_pid_{0};

    // ------------------------------------------------------------------
    // Process management
    // ------------------------------------------------------------------

    void spawn_module(const ModuleDescription& mod) {
        const ModuleDescriptor& desc = find_descriptor(mod.module_class);

        // Write temp ModuleConfig JSON for this instance
        std::string config_path = write_temp_config(mod);

        pid_t pid = ::fork();
        if (pid < 0)
            throw std::runtime_error("fork() failed for module '" + mod.name + "'");

        if (pid == 0) {
            // Child process
            const char* args[] = {desc.binary.c_str(), config_path.c_str(), nullptr};
            ::execv(desc.binary.c_str(), const_cast<char* const*>(args));
            // execv only returns on error
            std::cerr << "[Child] execv failed for: " << desc.binary << "\n";
            ::_exit(1);
        }

        std::cout << "[Launcher] Started '" << mod.name << "'"
                  << " (pid=" << pid << " binary="
                  << std::filesystem::path(desc.binary).filename().string() << ")\n";
        children_.push_back({pid, mod.name});
    }

    // ------------------------------------------------------------------
    // ModuleDescription → temp ModuleConfig JSON
    // ------------------------------------------------------------------

    std::string write_temp_config(const ModuleDescription& mod) {
        ModuleConfig cfg = to_config(mod);
        std::string json = rfl::json::write(cfg);

        std::string path = "/tmp/commrat_" + std::to_string(::getpid())
                         + "_" + mod.name + ".json";
        std::ofstream f(path);
        if (!f)
            throw std::runtime_error("Cannot write temp config: " + path);
        f << json;
        temp_files_.push_back(path);
        return path;
    }

    static ModuleConfig to_config(const ModuleDescription& desc) {
        ModuleConfig cfg;
        cfg.name = desc.name;

        if (desc.period_ms.has_value())
            cfg.period = std::chrono::milliseconds(*desc.period_ms);

        // Outputs
        if (desc.outputs.empty()) {
            cfg.outputs = NoOutputConfig{};
        } else if (desc.outputs.size() == 1) {
            const auto& o = desc.outputs[0];
            cfg.outputs = SimpleOutputConfig{.system_id   = o.system_id,
                                             .instance_id = o.instance_id};
        } else {
            MultiOutputConfig multi;
            for (const auto& o : desc.outputs)
                multi.addresses.push_back({.system_id   = o.system_id,
                                           .instance_id = o.instance_id});
            cfg.outputs = multi;
        }

        // Inputs
        if (desc.inputs.empty()) {
            cfg.inputs = NoInputConfig{};
        } else if (desc.inputs.size() == 1 && !desc.inputs[0].synced) {
            const auto& i = desc.inputs[0];
            cfg.inputs = SingleInputConfig{.source_system_id   = i.source_system_id,
                                           .source_instance_id = i.source_instance_id};
        } else {
            MultiInputConfig multi;
            for (const auto& i : desc.inputs)
                multi.sources.push_back({.system_id   = i.source_system_id,
                                         .instance_id = i.source_instance_id});
            cfg.inputs = multi;
        }

        return cfg;
    }

    void cleanup_temp_files() {
        for (const auto& p : temp_files_) ::unlink(p.c_str());
        temp_files_.clear();
    }

    // ------------------------------------------------------------------
    // Descriptor discovery
    // ------------------------------------------------------------------

    void scan_directory_for_descriptors(const std::string& dir) {
        if (!std::filesystem::is_directory(dir)) return;
        for (const auto& entry : std::filesystem::directory_iterator(dir)) {
            if (entry.path().extension() != ".json") continue;
            const std::string& p = entry.path().string();
            // Only load files ending in .module.json
            if (p.size() < 12) continue;
            if (p.substr(p.size() - 12) != ".module.json") continue;
            try_load_descriptor(p);
        }
    }

    void try_load_descriptor(const std::string& path) {
        auto result = rfl::json::load<ModuleDescriptor>(path);
        if (!result) return;  // Not a valid descriptor — skip silently
        ModuleDescriptor d = std::move(result.value());
        descriptors_[d.module_class] = std::move(d);
    }

    const ModuleDescriptor& find_descriptor(const std::string& module_class) const {
        auto it = descriptors_.find(module_class);
        if (it == descriptors_.end()) {
            std::string msg = "[Launcher] No descriptor found for module_class '"
                            + module_class + "'. Discovered classes:";
            for (const auto& [k, _] : descriptors_) msg += " " + k;
            throw std::runtime_error(msg);
        }
        return it->second;
    }

    // ------------------------------------------------------------------
    // AppDescription loading (JSON)
    // ------------------------------------------------------------------

    static AppDescription load_app_description(const std::string& path) {
        auto result = rfl::json::load<AppDescription>(path);
        if (!result)
            throw std::runtime_error("Failed to load AppDescription from '" + path
                                     + "': " + result.error().what());
        return std::move(result.value());
    }
};

} // namespace commrat
